version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1000
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
